on:
  workflow_dispatch
  push:
    branches:
      - 'main'
    tags:
      - 'v*'

jobs:
  build-and-push-pages:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build mkdocs site
        uses: heiafr-isc/mkdocs-edu-action@v1
